// Fictional examples for the actual Dashboard component; no live records.
const tasks = [
    [
        'open_deposit',
        'Open the deposit control',
        'Count the cash already in the drawer and start the shift.',
        '/deposit-control',
        'before',
        true,
        false,
        'Opened by Demo Cashier at 10:00 AM',
    ],
    [
        'stock',
        'Check the food stock and update the numbers',
        'Count what is on hand and correct the quantities in Inventory.',
        '/inventory',
        'before',
        false,
        true,
        'No stock movement recorded today.',
    ],
    [
        'expenses',
        'Record the pre-opening expenses',
        'Market runs, ice, gas and anything else paid before selling.',
        '/financial',
        'before',
        true,
        false,
        '2 expenses recorded today.',
    ],
    [
        'payroll',
        'Create the payroll and release the salary',
        'Prepare the payroll, then mark it paid so the cash leaves the ledger.',
        '/hris',
        'after',
        false,
        true,
        'No payroll released today.',
    ],
    [
        'close_deposit',
        'Close the deposit control',
        'Capture the closing balances, then count and submit the cash and GCash.',
        '/deposit-control',
        'after',
        false,
        false,
        'Shift still open.',
    ],
] as const;
export const checklist = {
    business_date: '2026-09-26',
    done: 2,
    total: 5,
    next: 'Check the food stock and update the numbers',
    steps: tasks.map(
        ([key, title, hint, href, phase, done, manual, detail]) => ({
            key,
            title,
            hint,
            href,
            phase,
            done,
            manual,
            detail,
            marked: false,
        }),
    ),
};
export const dashboard = {
    stats: {
        today_orders: 24,
        today_revenue: 4625,
        active_orders: 3,
        pending_orders: 1,
        preparing_orders: 2,
        ready_orders: 1,
        low_stock_count: 3,
        total_ingredients: 26,
    },
    recentOrders: Array.from({ length: 8 }, (_, i) => ({
        id: 1042 - i,
        queue_number: 42 - i,
        order_type: i % 2 ? 'takeout' : 'dine_in',
        status: [
            'pending',
            'preparing',
            'preparing',
            'ready',
            'completed',
            'completed',
            'completed',
            'completed',
        ][i],
        total_amount: 185 * ((i % 3) + 1),
        payment_status: i === 0 ? 'unpaid' : 'paid',
        items_count: (i % 3) + 1,
        created_at: '2026-09-26T12:00:00+08:00',
    })),
    pl: {
        revenue: 120000,
        cogs: 42000,
        gross_profit: 78000,
        expenses: 48000,
        net_profit: 30000,
        net_margin: 25,
    },
    servingTime: {
        avg_seconds: 480,
        completed_today: 20,
        fast_minutes: 5,
        slow_minutes: 15,
    },
    pendingProductBreakdown: [
        'Pork Monster Ribs',
        'Chicken Jerk',
        'Rice',
        'Ribs Platter',
        'Chicken Platter',
        'Extra Sauce',
    ].map((name, i) => ({ name, qty: i < 2 ? 2 : 1 })),
    depositShift: {
        id: 12,
        user_id: 1,
        user_name: 'Demo Cashier',
        is_mine: true,
        opened_at: '2026-09-26T10:00:00+08:00',
        closed_at: null,
        opening_cash: 1500,
        stage: 'counting' as const,
    },
    shiftChecklist: checklist,
};
